### ISSUE TITLE
Eslint highlights browser globals and jQuery $

### ISSUE THREAD

**Issue by salexzee** [BVAccel/clean-slate#11]
There are no environments set in .eslintrc so things like `$`, `window` and `document` get red underlines for being undeclared variables, when in fact they're globals that (in our case) we are safe to assume will exists. I can add the browser and jquery environments to .eslintrc, but first I want to make sure someone else isn't already working on it.

**Comment by cgaubuchon** [comment]
Good catch, for some reason the .jslint config from airbnb has these but the eslint config did not. Your PR LGTM
